{% set version = "1.6.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-swfscmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/swfscMisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/swfscMisc/swfscMisc_{{ version }}.tar.gz
  sha256: a49cb390643c4079f02986862eb2dfd33db4e6b6498e849bb418f73ffd6882e1

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-hdinterval
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-kknn
    - r-magrittr
    - r-mapdata
    - r-maps
    - r-rlang
    - r-sf
    - r-spatstat.geom
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-hdinterval
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-kknn
    - r-magrittr
    - r-mapdata
    - r-maps
    - r-rlang
    - r-sf
    - r-spatstat.geom
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('swfscMisc')"           # [not win]
    - "\"%R%\" -e \"library('swfscMisc')\""  # [win]

about:
  home: https://github.com/EricArcher/swfscMisc
  license: GPL-2.0-or-later
  summary: Collection of conversion, analytical, geodesic, mapping, and plotting functions. Used to support packages and code written by researchers at the Southwest Fisheries Science Center of the National Oceanic and Atmospheric Administration.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut

# Package: swfscMisc
# Type: Package
# Title: Miscellaneous Functions for Southwest Fisheries Science Center
# Description: Collection of conversion, analytical, geodesic, mapping, and plotting functions. Used to support packages and code written by researchers at the Southwest Fisheries Science Center of the National Oceanic and Atmospheric Administration.
# Version: 1.3
# Authors@R: c( EA = person("Eric", "Archer", email = "eric.archer@noaa.gov", role = c("aut", "cre")))
# URL: https://github.com/EricArcher/swfscMisc
# BugReports: https://github.com/EricArcher/swfscMisc/issues
# Depends: R (>= 3.2.3)
# Imports: graphics, grDevices, dplyr, ggplot2, ggrepel, mapdata, magrittr, tibble, maps, reshape2, rlang, spatstat, stats, tidyr, utils
# License: GPL (>= 2)
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2020-02-20 10:44:51 UTC; ericarcher
# Author: Eric Archer [aut, cre]
# Maintainer: Eric Archer <eric.archer@noaa.gov>
# Repository: CRAN
# Date/Publication: 2020-02-20 11:40:02 UTC
