appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Ou+ova08vFdcREVNfBmO3oJPRnnjurc9EFYCnQ5CAZQEPbqPttRGeBpZ5RXQXXPqvCbVqOO6IOezI54bfslUz9Tw6yx6N3KYbcmel7E4zPDySjPrb+DiBIp9rX1greMAv450un/VmH5gHWwxjeawtwBNQfGX9mHcTYKho9eennXosDrDhGwKun/JRySsQMj8n5G61sqjuw/GKp2YqlfEW/QFGNGNbL3AxQd9IbZLLEYtQIS8PEPm81yONox73UvR9BWzLInsgXK4ZOvSCdZlNOI2VGXNnf8nOJUvkdeeJw/4fJsS+E0pbXi90Gr7lzr2L0Buw9feC2R9W9MrmiDtdSiww9tSaHWTh4i/Kr500PlWTqcL843zN6P2/FRs0xRm7hBVg95Oj1Go73ih+29LaXmLPDEh1/gfEH2zleO7BA2nnS9rBEG2SO50ShLKMEB9VAjftTQ2tfMOQkYM4NHyrMbASFB2NWFYnSxNqU+PR1QKVBHsBsJ1ZpFh7BPPvtquxsFwTIvRQTbXusxnGlMydM8QpWloYeRpx9Sw8DPHwkI88nwYHaEZbChfGIamRPpWxq5MceX//jRPVjcJwDhdIG2DZ/KbUwJVIx/hR3GQ5/9ZmnqVrxxM9aByYw3UfHYi1xkteNC+0pXTBzNdDeiD0hs9hKBXPV0/gbnMDdrU8kY=
