travis:
  secure:
    BINSTAR_TOKEN: JNNbOzO64iO0ANSYBufuvT0OzjoaA+JwnlzZqYHFSSqHQ8fXCS7JAG4ND2uWVIC/KBlX//tntSj7KyyVLBRx1ukKU6hZx3Xr11ibxrlY5KnrqFU1O3yri95eLLycoQdGQAgOQjuWI85P3DEVzDt+cksZLF4kXzKiG0+XHq3Xfb5SlJA0h7rnLvBwRrr1JrZKVL8ZF9emplee3YYjbDJUMDbNN5dkdO/SGKy9eaa24H2hOvhdaY9Ff7zqQZNLcO9D9emap9v0eMDDOlxWmX3IubgRy/Sf9VLfS2xOzsI1g0UvbgHsO7zxEzNMRFTwknuwJc/we67ZfZ1fbkSG4DXivXI8Rxr8f0nCsHxUsTMsFR6JT0RDVi2fXfnJmCosI6QEeUduGzCxC0920DgyLDYjU40r+u7XD+4qsMp1npBFthGjXAAz/z5x4Cde+KG91ttbiwN/SeidMqTEzlLllUwukc1fwuDb2YwZls5lxN4vmBiTMYzSAx8NiqoOZxRIs4IbZ5yjZflQ56OZjiIyYKBA39Owi5TdAxIqxVNcSSQq4TTBUQQppfNcCJSIUGvk5GPqxhMSu0GWVs8bSMVoVqXCCZOKuSHuVfnQmy/+IO1YbF6FQ2FBeG8plyPl+WOb2Y+sW01hKVefB3dXpJEV763kNMToEOvkeUv42UAmgc+mQEg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
